---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list: ["recipe[rs-base::default]"]
  attributes: {}

- name: swap
  run_list: ["recipe[rs-base::swap]"]
  attributes : {}

- name: ntp
  run_list: ["recipe[rs-base::ntp]"]
  attributes : {}

- name: setup_syslog
  run_list: ["recipe[rs-base::setup_syslog]"]
  attributes : {}
