---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 2
    memory: 1024

platforms:
- name: ubuntu-14.04
  run_list: ['recipe[apt]']
  driver_config:
    box: opscode-ubuntu-14.04
- name: centos-7.0
  run_list: ['recipe[yum-epel]']
  driver_config:
    box: centos-7.0
- name: ubuntu-12.04
  run_list: ['recipe[apt]']
  driver_config:
    box: opscode-ubuntu-12.04
- name: centos-6.5
  run_list: ['recipe[yum-epel]']
  driver_config:
    box: opscode-centos-6.5

suites:
- name: default
  run_list: ['recipe[rs-base::default]']
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: rhel-6.5
  run_list: ['recipe[yum::epel]', 'recipe[fake::rhel_register]']
  driver_config:
    box: local-rhel-6.5
    box_url: file:///home/lopaka/opscode_rhel-6.5_chef-provisionerless.box
  attributes:
    cloud:
      provider: vagrant
    rs-base:
      collectd_server: sketchy1-66.rightscale.com
    fake:
      rhel_username: <%= ENV['RHEL_USERNAME'] %>
      rhel_password: <%= ENV['RHEL_PASSWORD'] %>
- name: swap
  run_list: ['recipe[rs-base::swap]']
  attributes:
    rs-base:
      collectd_server: sketchy1-66.rightscale.com
- name: ntp
  run_list: ['recipe[rs-base::ntp]']
  attributes : {}
- name: rsyslog_local
  run_list: ['recipe[rs-base::rsyslog]']
  attributes: {}
- name: rsyslog_remote
  run_list: ['recipe[rs-base::rsyslog]']
  attributes:
    rs-base:
      rsyslog_server: 192.168.0.1
- name: collectd
  run_list: ['recipe[fake::rightscale_software]', 'recipe[fake::tcpdump]', 'recipe[rs-base::collectd]']
  attributes:
    cloud:
      provider: vagrant
    rs-base:
      collectd_server: sketchy1-66.rightscale.com
