---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 1
    memory: 512
  ssh:
    insert_key: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
- name: centos-6.8
  run_list: ['recipe[yum-epel]','recipe[fake::create_secrets]']
  driver_config:
    box: bento/centos-6.8
- name: centos-7.2
  run_list: ['recipe[yum-epel]','recipe[fake::create_secrets]']
  driver_config:
    box: bento/centos-7.2
- name: ubuntu-14.04
  run_list: ['recipe[apt]','recipe[fake::create_secrets]']
  driver_config:
    box: bento/ubuntu-14.04
- name: ubuntu-16.04
  run_list: ['recipe[apt]','recipe[fake::create_secrets]']
  driver_config:
    box: bento/ubuntu-16.04

suites:
- name: default
  run_list: ['recipe[rs-base::default]']
  attributes:
    cloud:
      provider: vagrant
    rightscale:
      RS_RLL_PORT: 12345
    rs-base:
      swap:
        size: 1
- name: swap
  run_list: ['recipe[rs-base::swap]']
  attributes:
    rs-base:
      collectd_server: sketchy1-66.rightscale.com
- name: ntp
  run_list: ['recipe[rs-base::ntp]']
  attributes : {}
- name: rsyslog_local
  run_list: ['recipe[rs-base::rsyslog]']
  attributes: {}
- name: rsyslog_remote
  run_list: ['recipe[rs-base::rsyslog]']
  attributes:
    rs-base:
      rsyslog_server: 192.168.0.1
- name: collectd
  run_list: ['recipe[fake::tcpdump]', 'recipe[rs-base::monitoring_collectd]']
  attributes:
    rightscale:
      RS_RLL_PORT: 12345
    cloud:
      provider: vagrant
